[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "llmflowstack"
version = "1.3.0"
authors = [
  { name = "Gustavo Henrique Ferreira Cruz", email = "gustavohferreiracruz@gmail.com" }
]
description = "LLMFlowStack is a framework for training and using LLMs (LLaMA, GPT-OSS, Gemma, ...). Supports DAPT, fine-tuning, and distributed inference."
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}

dependencies = [
  "accelerate",
  "bert-score",
  "bitsandbytes",
  "chromadb",
  "datasets",
  "evaluate",
  "fbgemm_gpu_genai",
  "kernels",
  "langchain-chroma",
  "langchain_community",
  "nltk",
  "peft",
  "pillow",
  "rouge-score",
  "safetensors",
  "scikit-learn",
  "sentence-transformers",
  "torch",
  "torchao",
  "transformers",
  "triton",
  "trl",
]